### ISSUE TITLE
cacheing transformed mapping files

### ISSUE THREAD

**Issue by AlexanderPico** [nrnb/target-interaction-finder#1]
Since the initial transformation of the xgmml mapping files takes ~20 seconds and will rarely change (once a year?), I wonder if it's worthwhile saving the transformed data as a new file that can be read more quickly per run.

**Comment by ariutta** [comment]
By "caching", do you mean serializing the in-memory networkx data structure and saving it to a file?

**Comment by AlexanderPico** [comment]
Yes, serializing whatever data structure is easier/faster to read and put back in memory. I'm assuming here that part of the time (more like 20-40 seconds) is in data transformation and perhaps even intermediate data structures.

If there isn't a serialized form of the data that would be read faster, then this is a bad idea and can be ignored :)

**Comment by ariutta** [comment]
We could write out as pickle:
http://networkx.github.io/documentation/latest/reference/generated/networkx.readwrite.gpickle.write_gpickle.html
