### ISSUE TITLE
Some xgmmls fail to open in Cytoscape

### ISSUE THREAD

**Issue by AlexanderPico** [nrnb/target-interaction-finder#4]
Lines: like this:
`<att name="identifiers" value="IFN-&lt;ALPHA&gt2" type="string" />`

Are causing errors like this:
`Caused by: org.xml.sax.SAXException: Fatal parsing error on line 64157 -- 'The reference to entity "gt2" must end with the ';' delimiter.'`

Tried attaching example xgmml (with .png ext)...
![microcosm-hsa-2012-12-05-results xgmml](https://cloud.githubusercontent.com/assets/1418193/6909289/61eb5baa-d6f9-11e4-92c6-d49b1d867194.png)

**Comment by ariutta** [comment]
Moved issue over to the [networkxxgmml issue tracker](https://github.com/informationsea/networkxxgmml/issues/2).

**Comment by ariutta** [comment]
Will keep this open until it's fixed, but the comments should happen on the other issue tracker.
